### PR TITLE
Training Parameter A

### PR DESCRIPTION
**Pull request by kaf0005**
This PR trains A during the training phase of BRER based on training time. The current training time for training of A is set to 20ns with default A value of 0.2. A is also pair specific for each DEER distance. Each A value is saved in a dictionary as either rejected or accepted. This memory allows for future iterations to choose acceptable A values for target sets that were already ran through BRER.

### CODE REVIEW

**Comment by kaf0005** [comment]
So you would like the max_train_time (ps) and the increase_A to be user inputs via run.py? It might take me a little to figure out a user input for sample restraint then.

**Comment by jmhays** [comment]
Right. I think you should be able to look at the other general (not pair-specific) parameters and see how they are passed from run.py through to the plugins. I would just `grep` a parameter in the source code and see all the places where it shows up:
```
grep -R "tau" run_brer/run_brer/
grep -R "tau" sample_restraint/src
```

**Comment by jmhays** [comment]
The simulation does not move to the convergence phase after training is complete (all pairs have "accepted" values of A).

Output from Frontera:
[frontera_tests.tar.gz](https://github.com/jmhays/run_brer/files/3428177/frontera_tests.tar.gz)

**Comment by kaf0005** [comment]
The convergeDist variable was fixed so that the training run will realize when all three distances have converged; I have also made it so that the same value of A will not be rerecorded in the dictionary. This will ensure that once we have done several iterations of brer that the dictionary will not get too big to manage.

**Pull request merged**
